stages:
  - build
      
build_win:
  stage: build
  only: 
  - tags
  tags:
  - win10unity
  before_script:
   - mkdir deployment-helpers
   - cd deployment-helpers
   - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@baltig.viaccess-orca.com:8443/VRT/deployment-group/Deployment
   - python -m pip install -r Deployment/scripts/requirements.txt
   - cd ..
  script:
    - bash build-VRTogether.sh
    - mkdir deliverables
    - Compress-Archive built-VRTogether  deliverables/vrtogether_win1064_$CI_COMMIT_TAG.zip
    - python deployment-helpers/Deployment/scripts/addReleaseToGitLab --cicd --notag vrtogether_win1064_$CI_COMMIT_TAG.zip
