stages:
  - build
#  - test
#  - deploy
      
build_win:
  stage: build
  only: 
  - tags
  tags:
  - win10unity
  before_script:
   - mkdir deployment-helpers
   - cd deployment-helpers
   - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@baltig.viaccess-orca.com:8443/VRT/deployment-group/Deployment
   - python -m pip install -r Deployment/scripts/requirements.txt
   - cd ..
  script:
    - bash build-VRTogether.sh
    - mkdir deliverables
    - Compress-Archive built-VRTogether  deliverables/vrtogether_win1064_$CI_COMMIT_TAG.zip
    - python deployment-helpers/Deployment/scripts/addReleaseToGitLab --cicd --notag vrtogether_win1064_$CI_COMMIT_TAG.zip
#  artifacts:
#    paths:
#      - vrtogether_win1064_$CI_COMMIT_TAG.zip
      
#deploy_all:
#  stage: deploy
#  tags:
#  - linux
#  only: 
#  - tags
#  except: 
#  - /latest/
#  dependencies: 
#  - build_win
#  before_script:
#  - apt-get update
#  - apt-get install -y python3-pip
#  - mkdir deployment-helpers
#  - cd deployment-helpers
#  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@baltig.viaccess-orca.com:8443/VRT/deployment-group/Deployment
#  - python3 -m pip install -r Deployment/scripts/requirements.txt
#  - cd ..
#  script:
#    - mkdir deliverables
#    - mv cwipc_util_ubuntu1804_$CI_COMMIT_TAG.tgz cwipc_util_osx1014_$CI_COMMIT_TAG.tgz cwipc_util_win1064_$CI_COMMIT_TAG.zip deliverables
#    - python3 deployment-helpers/Deployment/scripts/addReleaseToGitLab --cicd --notag cwipc_util_ubuntu1804_$CI_COMMIT_TAG.tgz cwipc_util_osx1014_$CI_COMMIT_TAG.tgz cwipc_util_win1064_$CI_COMMIT_TAG.zip
#      
#deploy_all_untagged:
#  stage: deploy
#  tags:
#  - linux
#  except: 
#  - tags
#  - /latest/
#  dependencies: 
#  - build_linux
#  - build_osx
#  - build_win
#  before_script:
#  - apt-get update
#  - apt-get install -y python3-pip
#  - mkdir deployment-helpers
#  - cd deployment-helpers
#  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@baltig.viaccess-orca.com:8443/VRT/deployment-group/Deployment
#  - python3 -m pip install -r Deployment/scripts/requirements.txt
#  - cd ..
#  script:
#    - mkdir deliverables
#    - mv cwipc_util_ubuntu1804_$CI_COMMIT_TAG.tgz cwipc_util_osx1014_$CI_COMMIT_TAG.tgz cwipc_util_win1064_$CI_COMMIT_TAG.zip deliverables
#    - python3 deployment-helpers/Deployment/scripts/addReleaseToGitLab --cicd --tag_name latest --release_name latest --deleterelease || true
#    - python3 deployment-helpers/Deployment/scripts/addReleaseToGitLab --cicd --tag_name latest --release_name latest --deletetag || true
#    - python3 deployment-helpers/Deployment/scripts/addReleaseToGitLab --cicd --tag_name latest --release_name latest --branch_to_tag "$CI_COMMIT_REF_NAME" cwipc_util_ubuntu1804_$CI_COMMIT_TAG.tgz cwipc_util_osx1014_$CI_COMMIT_TAG.tgz cwipc_util_win1064_$CI_COMMIT_TAG.zip
